export enum StatusServico {
  EM_ANALISE = 'EM_ANALISE',
  AGENDADA = 'AGENDADA',
  INICIADA = 'INICIADA',
  FINALIZADA = 'FINALIZADA',
  CANCELADA = 'CANCELADA',
  RECUSADA = 'RECUSADA',
  EXPIRADA = 'EXPIRADA',
}
